import React from 'react'
import './FeaturedSection.css';
import ProjectCard from './ProjectCard';
import {Link} from 'react-router-dom';

function FeaturedSection() {
  return (
    <div className="featured-section">
        <h3>Featured projects</h3>
        <div className="cards">
            <ProjectCard
                title={"NFC contact card"}
                tags={["hardware"]}
                description={"A PCB contact card that can be used to share contact information with others by tapping it to their phone"}
                fullDescriptionPath={"../../content/nfc.md"}
                img={"../../imgs/contact-card.jpg"}
            />
            <ProjectCard 
                title={"Gaze-controlled game"}
                tags={["neurotech, hardware"]}
                description={"This chrome dinosaur game is controlled hands-free using EOG-signals generated by the brain"}
                fullDescriptionPath={"../../content/eog.md"}
                img={"../../imgs/dino-game.gif"}
            />
            <ProjectCard 
                title={"Cal Hacks 8.0 badge"}
                tags={["hardware"]}
                description={"Interactive conference badge assembled by hackathon workshop attendees"}
                fullDescriptionPath={"../../content/badge.md"}
                img={"../../imgs/badge.gif"}
            />
        </div>
        
        <div className="more-projects">
            <Link to="/projects">
                <h5>more projects</h5>
                <i class="fa fa-external-link" aria-hidden="true"></i> 
            </Link>
        </div>

    </div>
  )
}

export default FeaturedSection;