import React, {useState, useEffect} from 'react';
import './Projects.css';
import PostPreview from './PostPreview';
import Select from 'react-select';

var selected_tags = [];

const nfc_card = {
    title: "NFC contact card",
    tags: ["hardware"],
    description: "Contact PCB card with NFC chip and an LED",
    fullDescriptionPath: "../../content/nfc.md",
    img: "../../imgs/contact-card.jpg"
}
const eog_game = {
    title: "Gaze-controlled game",
    tags: ["neurotech"],
    description: "This chrome dinosaur game is controlled hands-free using EOG-signals generated by the brain",
    fullDescriptionPath: "../../content/eog.md",
    img: "../../imgs/dino-game.gif"
}

const badge = {
    title: "Cal Hacks 8.0 badge",
    tags: ["hardware"],
    description: "Interactive conference badge assembled by hackathon workshop attendees",
    fullDescriptionPath: "../../content/badge.md",
    img: "../../imgs/badge.gif"
}

const cansat2016 = {
    title: "Cansat 2016",
    tags: ["team project", "hardware", "software"],
    description: "Atmospheric probe with sensors and a mechanism for spreading mustard seeds",
    img: "../../imgs/cansat2016.jpg"
}

const cansat2017 = {
    title: "Cansat 2017",
    tags: ["team project", "hardware", "software"],
    description: "Atmospheric probe with sensors capable of measuring soil resistance and temperature upon landing",
    img: "../../imgs/cansat2017.jpg"
}

const cansat2018 = {
    title: "Cansat 2018",
    tags: ["team project", "hardware", "software"],
    description: "1 kg version of an atmospheric probe with sensors and a custom-designed spectrometer",
    img: "../../imgs/cansat2018.jpg"
}

const copter = {
    title: "CopterHack",
    tags: ["hackathon project", "computer vision"],
    description: "Autonomous drone assembled and programmed in a weekend during a hackathon",
    img: "../../imgs/copter.jpg"
}

const hat = {
    title: "Raspberry Pi hat",
    tags: ["hardware"],
    description: "Add-on module for Raspberry Pi to support a system for autonomous testing of multiple boards",
    img: "../../imgs/hat.jpg"
}

const robot1 = {
    title: "Delivery robot",
    tags: ["hackathon project", "software"],
    description: "Remote-controlled robot with object-grasping capabilities",
    img: "../../imgs/robot1.gif"
}

const robot2 = {
    title: "Line-following robot",
    tags: ["hackathon project", "software"],
    description: "Autonomous line-follower robot capable of obstacle avoidance",
    img: "../../imgs/robot2.jpg"
}

const remote = {
    title: "Remote control",
    tags: ["personal project", "hardware"],
    description: "Remote control for a robot with a custom-designed PCB",
    img: "../../imgs/remote.jpg"
}

const sixt33n = {
    title: "SIXT33N on Mars",
    tags: ["class project", "software"],
    description: "SP21 TI Design contest submission, 1st Place",
    img: "../../imgs/sixt33n.jpg"
}

const wall_climber = {
    title: "Wall-climbing robot",
    tags: ["class project", "hardware", "3D modeling"],
    description: "Final project for an engineering design course I took my senior year of high school",
    img: "../../imgs/wall-climber.jpg"
}

const eog_pcb = {
    title: "PCB for recording EOG signals",
    tags: ["team project", "hardware"],
    description: "Analog front end (AFE) circuit tuned for recording electrooculogram (EOG) signals",
    img: "../../imgs/eog.png"
}

const byow = {
    title: "Build your own world",
    tags: ["personal project", "software", "Java"],
    description: "",
    img: "../../imgs/byow.png"
}

const olympiad = {
    title: "Robot tracker",
    tags: ["personal project", "software", "C++", "computer vision"],
    description: "",
    img: "../../imgs/robotics-olympiad.png"
}

const robot3 = {
    title: "Remote controlled robot",
    tags: ["personal project", "hardware"],
    description: "",
    img: "../../imgs/rc-robot.png"
}

const website = {
    title: "ingarobotics.com",
    tags: ["personal project", "software", "React"],
    description: "",
    img: "../../imgs/website.png"
}



const projects = [nfc_card, eog_game, badge, cansat2016, cansat2017, cansat2018, copter, hat, robot1, robot2, remote, sixt33n, wall_climber, eog_pcb, byow, olympiad, robot3, website];

const options = [
    { borderColor: '#6AAADF', backgroundColor: '#304469', textColor: '#D3EBEC', value: 'all projects', label: 'all projects' },
    { borderColor: '#9F9FF8', backgroundColor: '#453061', textColor: '#FEF6FE', value: 'personal project', label: 'personal project' },
    { borderColor: '#80CE93', backgroundColor: '#385841', textColor: '#D7DDD9', value: 'neurotech', label: 'neurotech' },
    { borderColor: '#F2C45D', backgroundColor: '#836534', textColor: '#FFFABC', value: 'software', label: 'software' },
    { borderColor: '#ED9AB6', backgroundColor: '#62344B', textColor: '#FDE6FB', value: 'hardware', label: 'hardware' },
    { borderColor: '#EF8452', backgroundColor: '#7E4F27', textColor: '#E5DBD4', value: 'hackathon project', label: 'hackathon project' },
    { borderColor: '#DF3D30', backgroundColor: '#642D24', textColor: '#F5DFD3', value: 'class project', label: 'class project' }
]

const customStyles = {
    control: (defaultStyles) => ({
        ...defaultStyles,
        backgroundColor: "#272626",
        borderRadius: 5,
        padding: "5px",
        border: "1px, #a0a0a0",
        boxShadow: "none",
    }),

    option: (defaultStyles, state) => ({
        ...defaultStyles,
        color: state.isSelected ? "#212529" : "#fff",
        backgroundColor: state.isSelected ? "#a0a0a0" : "#404040",

        ":hover": {
            ...defaultStyles[":hover"],
            backgroundColor: "#a0a0a0",
        },

        //color: state.data.textColor,
        //backgroundColor: state.data.backgroundColor,
        //borderRadius: 5,
        //width: "fit-content",
        //margin: "2px 2px 2px",
        //borderLeft: `4px solid ${state.data.borderColor}`,
    }),

    multiValue: (defaultStyles, state) => ({
        ...defaultStyles,
        backgroundColor: state.data.backgroundColor,
        borderLeft: `4px solid ${state.data.borderColor}`,
        borderRightRadius: 5,
        display: "flex",
        width: "fit-content",
    }),

    multiValueLabel: (defaultStyles, state) => ({
        ...defaultStyles,
        color: state.data.textColor,
        fontSize: "0.9rem",
    }),
};

var filteredProjects = [];

const ProjectsIntro = () => {
    const [selectedOption, setSelectedOption] = useState("")

    var handleChange = (selectedOption) => {
        setSelectedOption(selectedOption.value);
        selected_tags = [];
        for (var i = 0; i < selectedOption.length; i++) {
            selected_tags.push(selectedOption[i].value);
        }
        //console.log(selected_tags);
    };

    
  return (
    <div className="projects-intro">
        <h3>A directory of my personal and team projects.</h3>
        <div className="drop-down-menu">
            <Select 
                isMulti 
                onChange={handleChange} 
                options={options} 
                styles={customStyles} 
                defaultValue={[options[0]]}
            />
        </div>
        <div className="projects-list">
            <PostPreview
                title={nfc_card.title}
                tags={nfc_card.tags}
                description={nfc_card.description}
                img={nfc_card.img}
            />
            <PostPreview
                title={eog_game.title}
                tags={eog_game.tags}
                description={eog_game.description}
                img={eog_game.img}
            />
            <PostPreview
                title={badge.title}
                tags={badge.tags}
                description={badge.description}
                img={badge.img}
            />
            <PostPreview
                title={cansat2016.title}
                tags={cansat2016.tags}
                description={cansat2016.description}
                img={cansat2016.img}
            />
            <PostPreview
                title={cansat2017.title}
                tags={cansat2017.tags}
                description={cansat2017.description}
                img={cansat2017.img}
            />
            <PostPreview
                title={cansat2018.title}
                tags={cansat2018.tags}
                description={cansat2018.description}
                img={cansat2018.img}
            />
            <PostPreview
                title={copter.title}
                tags={copter.tags}
                description={copter.description}
                img={copter.img}
            />
            <PostPreview
                title={hat.title}
                tags={hat.tags}
                description={hat.description}
                img={hat.img}
            />
            <PostPreview
                title={robot1.title}
                tags={robot1.tags}
                description={robot1.description}
                img={robot1.img}
            />
            <PostPreview
                title={robot2.title}
                tags={robot2.tags}
                description={robot2.description}
                img={robot2.img}
            />
            <PostPreview
                title={remote.title}
                tags={remote.tags}
                description={remote.description}
                img={remote.img}
            />
            <PostPreview
                title={sixt33n.title}
                tags={sixt33n.tags}
                description={sixt33n.description}
                img={sixt33n.img}
            />
            <PostPreview
                title={wall_climber.title}
                tags={wall_climber.tags}
                description={wall_climber.description}
                img={wall_climber.img}
            />
            <PostPreview
                title={eog_pcb.title}
                tags={eog_pcb.tags}
                description={eog_pcb.description}
                img={eog_pcb.img}
            />
            <PostPreview
                title={byow.title}
                tags={byow.tags}
                description={byow.description}
                img={byow.img}
            />
            <PostPreview
                title={olympiad.title}
                tags={olympiad.tags}
                description={olympiad.description}
                img={olympiad.img}
            />
            <PostPreview
                title={robot3.title}
                tags={robot3.tags}
                description={robot3.description}
                img={robot3.img}
            />
            <PostPreview
                title={website.title}
                tags={website.tags}
                description={website.description}
                img={website.img}
            />


        </div>
    </div>
  )
}

export default ProjectsIntro;