import React, {useState, useEffect} from 'react';
import './Projects.css';
import PostPreview from './PostPreview';
import Select from 'react-select';

var selected_tags = [];

const nfc_card = {
    title: "NFC contact card",
    tags: ["hardware"],
    description: "A PCB contact card that can be used to share contact information with others by tapping it to their phone",
    fullDescriptionPath: "../../content/nfc.md",
    img: "../../imgs/contact-card.jpg"
}
const eog_game = {
    title: "Gaze-controlled game",
    tags: ["neurotech"],
    description: "This chrome dinosaur game is controlled hands-free using EOG-signals generated by the brain",
    fullDescriptionPath: "../../content/eog.md",
    img: "../../imgs/dino-game.gif"
}

const badge = {
    title: "Cal Hacks 8.0 badge",
    tags: ["hardware"],
    description: "Interactive conference badge assembled by hackathon workshop attendees",
    fullDescriptionPath: "../../content/badge.md",
    img: "../../imgs/badge.gif"
}

const cansat2016 = {
    title: "Cansat 2016",
    tags: ["team project", "hardware", "software"],
    description: "Atmospheric probe with sensors and a mechanism for spreading mustard seeds",
    img: "../../imgs/cansat2016.jpg"
}

const cansat2017 = {
    title: "Cansat 2017",
    tags: ["team project", "hardware", "software"],
    description: "Atmospheric probe with sensors capable of measuring soil resistance and temperature upon landing",
    img: "../../imgs/cansat2017.jpg"
}

const cansat2018 = {
    title: "Cansat 2018",
    tags: ["team project", "hardware", "software"],
    description: "1 kg version of an atmospheric probe with sensors and a custom-designed spectrometer",
    img: "../../imgs/cansat2018.jpg"
}

const projects = [nfc_card, eog_game, badge, cansat2016, cansat2017, cansat2018];

const options = [
    { borderColor: '#6AAADF', backgroundColor: '#304469', textColor: '#D3EBEC', value: 'all projects', label: 'all projects' },
    { borderColor: '#9F9FF8', backgroundColor: '#453061', textColor: '#FEF6FE', value: 'personal project', label: 'personal project' },
    { borderColor: '#80CE93', backgroundColor: '#385841', textColor: '#D7DDD9', value: 'neurotech', label: 'neurotech' },
    { borderColor: '#F2C45D', backgroundColor: '#836534', textColor: '#FFFABC', value: 'software', label: 'software' },
    { borderColor: '#ED9AB6', backgroundColor: '#62344B', textColor: '#FDE6FB', value: 'hardware', label: 'hardware' },
    { borderColor: '#EF8452', backgroundColor: '#7E4F27', textColor: '#E5DBD4', value: 'hackathon project', label: 'hackathon project' },
    { borderColor: '#DF3D30', backgroundColor: '#642D24', textColor: '#F5DFD3', value: 'class project', label: 'class project' }
]

const customStyles = {
    control: (defaultStyles) => ({
        ...defaultStyles,
        backgroundColor: "#272626",
        borderRadius: 5,
        padding: "5px",
        border: "1px, #a0a0a0",
        boxShadow: "none",
    }),

    option: (defaultStyles, state) => ({
        ...defaultStyles,
        color: state.isSelected ? "#212529" : "#fff",
        backgroundColor: state.isSelected ? "#a0a0a0" : "#404040",

        ":hover": {
            ...defaultStyles[":hover"],
            backgroundColor: "#a0a0a0",
        },

        //color: state.data.textColor,
        //backgroundColor: state.data.backgroundColor,
        //borderRadius: 5,
        //width: "fit-content",
        //margin: "2px 2px 2px",
        //borderLeft: `4px solid ${state.data.borderColor}`,
    }),

    multiValue: (defaultStyles, state) => ({
        ...defaultStyles,
        backgroundColor: state.data.backgroundColor,
        borderLeft: `4px solid ${state.data.borderColor}`,
        borderRightRadius: 5,
        display: "flex",
        width: "fit-content",
    }),

    multiValueLabel: (defaultStyles, state) => ({
        ...defaultStyles,
        color: state.data.textColor,
        fontSize: "0.9rem",
    }),
};

var filteredProjects = [];

const ProjectsIntro = () => {
    const [selectedOption, setSelectedOption] = useState("")

    var handleChange = (selectedOption) => {
        setSelectedOption(selectedOption.value);
        selected_tags = [];
        for (var i = 0; i < selectedOption.length; i++) {
            selected_tags.push(selectedOption[i].value);
        }
        //console.log(selected_tags);
    };

    
  return (
    <div className="projects-intro">
        <h3>A directory of my personal and team projects.</h3>
        <div className="drop-down-menu">
            <Select 
                isMulti 
                onChange={handleChange} 
                options={options} 
                styles={customStyles} 
                defaultValue={[options[0]]}
            />
        </div>
        <div className="projects-list">
            <PostPreview
                title={nfc_card.title}
                tags={nfc_card.tags}
                description={nfc_card.description}
                img={nfc_card.img}
            />
            <PostPreview
                title={eog_game.title}
                tags={eog_game.tags}
                description={eog_game.description}
                img={eog_game.img}
            />
            <PostPreview
                title={badge.title}
                tags={badge.tags}
                description={badge.description}
                img={badge.img}
            />
            <PostPreview
                title={cansat2016.title}
                tags={cansat2016.tags}
                description={cansat2016.description}
                img={cansat2016.img}
            />
            <PostPreview
                title={cansat2017.title}
                tags={cansat2017.tags}
                description={cansat2017.description}
                img={cansat2017.img}
            />
            <PostPreview
                title={cansat2018.title}
                tags={cansat2018.tags}
                description={cansat2018.description}
                img={cansat2018.img}
            />


        </div>
    </div>
  )
}

export default ProjectsIntro;